server:
    port: 8787
    servlet:
        context-path: /lanchonete


spring:
    datasource:
        username: postgres
        password: 123456
        url: jdbc:postgresql://localhost:5429/lanchonete

    security:
        oauth2:
            client:
                registration:
                    google:
                        client_id: "lembrar de fazer o acesso no google api console e pega o id e secret"
                        client_secret:
jpa:
    properties:
        show-sql: true
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQlDialect
flyway:
    baselineOnMigrate: true
    check-location: true
    schemas: public
    enabled: true

springdoc:
    swagger-ui:
        path: /swagger-ui-custom.html





