server:
    servlet:
        context-path: /lanchonete


spring:
    datasource:
        username: postgres
        password: 123456
        url: jdbc:postgresql:localhost:5429
jpa:
    properties:
        show-sql: true
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQlDialect
flyway:
    baselineOnMigrate: true
    check-location: true
    schemas: public
    enabled: true




